### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by flashdude098** [sourcelocation/Picasso-v3#3]
[Picasso-2023-12-08-150715.txt](https://github.com/sourcelocation/Picasso-v3/files/13624826/Picasso-2023-12-08-150715.txt)

**Comment by flashdude098** [comment]
New crash log 
[Picasso-2023-12-10-030925.txt](https://github.com/sourcelocation/Picasso-v3/files/13624883/Picasso-2023-12-10-030925.txt)

**Comment by sourcelocation** [comment]
No details provided.
