### ISSUE TITLE
App crashes after enabling Background Applying

### ISSUE THREAD

**Issue by skadz108** [sourcelocation/Picasso-v3#4]
iPhone 14 Pro, iOS 16.6b1, Picasso v3.1

I have been able to confirm a consistent issue when enabling Background Applying in the settings. The app shows the explanation pop up for the Location and Notification permissions, but crashes after pressing Continue.

Despite switching to User registration in TrollStore to grant the necessary permissions and switching back to System, the setting still remains disabled in the app.

If any further information is required, please leave a comment.

**Comment by sourcelocation** [comment]
Need a crash log.

**Comment by skadz108** [comment]
[Picasso-2023-12-09-171009.txt](https://github.com/sourcelocation/Picasso-v3/files/13626060/Picasso-2023-12-09-171009.txt)

Here's the latest crash log from the test I just did.

**Comment by sourcelocation** [comment]
Can replicate the crash. I will now start debugging it
