### ISSUE TITLE
System icons don’t theme in switcher when "customize system app" enabled

### ISSUE THREAD

**Issue by rctfan929** [sourcelocation/Picasso-v3#7]
When I turn on "customize system apps" some system apps don’t theme in the app switcher.

iPad 8th gen
iOS 16.5

![IMG_0012](https://github.com/sourcelocation/Picasso-v3/assets/46878212/77181239-8853-43cf-b287-5ef5f4d0eb9b)

**Comment by sourcelocation** [comment]
Hi, sadly this is a limitation of kfd, as after some time the icons revert back. The cache stays the same, but app switcher always refreshes them, meaning after some time it will show the original icons. Same applies for notifications.
