### ISSUE TITLE
Error when creating account 

### ISSUE THREAD

**Issue by ComeOnBear** [sourcelocation/Picasso-v3#8]
Installed with trollstore 2, iOS 17.0
![IMG_2880](https://github.com/sourcelocation/Picasso-v3/assets/34274925/c968599d-0029-4a8b-87d3-e449776e06fa)

**Comment by sourcelocation** [comment]
Use website for now. https://repo.sourceloc.net

**Comment by UseUser123321** [comment]
> Use website for now. https://repo.sourceloc.net

the website errors for me when creating an account

**Comment by sourcelocation** [comment]
Download open source builds from https://github.com/skadz108/OpenPicasso-Builds
